### ISSUE TITLE
View Products

### ISSUE THREAD

**Issue by trxdave** [trxdave/cycleshop#1]
As a User, I want to **to view all products,** so that I can **browse through available items.**

**Tasks**

- [x] Implement pagination on the product listing page, showing a set number of products per page.
- [x] Add “Previous” and “Next” buttons for easy navigation between pages.
- [ ] Display the current page number to help users keep track.
- [x] Add a search bar at the top of the product listing page
- [x] Add a rating display (out of 5 stars) on each product detail page.
- [ ] Aggregate and display average ratings if the product has multiple reviews.
- [x] Add a “Add to Wishlist” button on each product detail page.
- [x] Provide a link to view the wishlist from the user’s account page.
