### ISSUE TITLE
Delete Products from the catalog - Product Management

### ISSUE THREAD

**Issue by trxdave** [trxdave/cycleshop#10]
As Site Administrator, I want to **delete products from the catalog,** so that I can **remove discontinued items.**

**Tasks**

- [x] Add a delete_product view to handle the deletion of products.
- [x] Implement a “Delete” button on the product detail and list pages.
- [x] Add a confirmation dialog to verify deletion actions.
- [x] Show a message indicating a successful deletion.
- [x] Set up notifications for the administrator when products are deleted.
