### ISSUE TITLE
Subscribe to the newsletter

### ISSUE THREAD

**Issue by trxdave** [trxdave/cycleshop#18]
As a User, I want to **subscribe to the newsletter,** so that I can **receive updates about new products and promotions.**

**Task**

- [x] Create a subscription form with a single email field.
- [x] Add the form to the homepage and footer for easy access.
- [x] Set up validation to ensure only valid email addresses can be submitted.
- [x] Add error messages for invalid emails or if the email is already subscribed.
- [x] Include a thank-you message and brief overview of what to expect in the emails.
