### ISSUE TITLE
Remove items from cart

### ISSUE THREAD

**Issue by trxdave** [trxdave/cycleshop#4]
As a User, I want **to remove items from my cart** so that I can **modify my order before checkout.**

**Tasks**

- [x] Create a “Remove” button for each item displayed in the shopping cart.
- [x] Implement functionality to remove an item from the cart when the “Remove” button is clicked.
- [x] Display a confirmation message when an item is successfully removed from the cart.
