### ISSUE TITLE
Add new products - project management

### ISSUE THREAD

**Issue by trxdave** [trxdave/cycleshop#8]
As a Site Administrator, I want to **add new products,** so that I can **keep my product catalog up to date**

**Tasks**

- [x] Design the “Add Product” form, including fields for product name, description, price,  quantity, category, and image upload.
- [x] Add backend functionality to save new products in the database.
- [x] Include pagination for the product list to ensure ease of navigation.
- [x] Add an “Edit Product” button on each product entry in the product list.
- [x] Add a “Delete” button for each product in the product list.
- [x] Add a “Category” field in the “Add Product” and “Edit Product” forms.
